# Generated by Django 5.2.1 on 2025-05-22 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizPlugin', '0002_category_question_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('score', models.IntegerField()),
                ('correction', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quizPlugin.question')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('min_score', models.IntegerField()),
                ('questions', models.ManyToManyField(related_name='tests', to='quizPlugin.question')),
            ],
        ),
        migrations.CreateModel(
            name='TestExecution',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('execution_time', models.DateTimeField(auto_now_add=True)),
                ('age', models.IntegerField()),
                ('score', models.IntegerField()),
                ('ip', models.GenericIPAddressField()),
                ('duration', models.DurationField()),
                ('revision_date', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField()),
                ('given_answer', models.ManyToManyField(related_name='test_executions', to='quizPlugin.answer')),
                ('sex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_executions', to='quizPlugin.sex')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_executions', to='quizPlugin.test')),
            ],
        ),
    ]
