# Generated by Django 5.2.1 on 2025-05-24 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizPlugin', '0004_alter_answer_id_alter_category_id_alter_question_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testexecution',
            name='given_answer',
        ),
        migrations.CreateModel(
            name='GivenAnswer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizPlugin.answer')),
                ('test_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizPlugin.testexecution')),
            ],
        ),
    ]
