# Generated by Django 5.2.1 on 2025-05-26 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizPlugin', '0006_alter_testexecution_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Risposta', 'verbose_name_plural': 'Risposte'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorie'},
        ),
        migrations.AlterModelOptions(
            name='givenanswer',
            options={'verbose_name': 'Risposta Data', 'verbose_name_plural': 'Risposte Date'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Domanda', 'verbose_name_plural': 'Domande'},
        ),
        migrations.AlterModelOptions(
            name='sex',
            options={'verbose_name': 'Sesso', 'verbose_name_plural': 'Sesso'},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name': 'Test', 'verbose_name_plural': 'Tests'},
        ),
        migrations.AlterModelOptions(
            name='testexecution',
            options={'ordering': ['-execution_time'], 'verbose_name': 'Esecuzione Test', 'verbose_name_plural': 'Esecuzioni Test'},
        ),
        migrations.AlterField(
            model_name='answer',
            name='score',
            field=models.IntegerField(choices=[(-1, 'Seious Error'), (0, 'Error'), (1, 'Correct')]),
        ),
    ]
