# Generated by Django 5.2.1 on 2025-05-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizPlugin', '0007_alter_answer_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='score',
            field=models.IntegerField(choices=[(-1, 'Serious Error'), (0, 'Error'), (1, 'Correct')]),
        ),
    ]
