# Generated by Django 5.2.1 on 2025-05-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizPlugin', '0008_alter_answer_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='testexecution',
            name='revision_code',
            field=models.CharField(blank=True, editable=False, max_length=12, unique=True),
        ),
    ]
