# Generated by Django 5.2.1 on 2025-05-26 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizPlugin', '0009_testexecution_revision_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testexecution',
            name='revision_code',
            field=models.CharField(blank=True, max_length=12, unique=True),
        ),
    ]
