# Generated by Django 5.2.1 on 2025-05-26 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizPlugin', '0010_alter_testexecution_revision_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testexecution',
            name='age',
            field=models.IntegerField(verbose_name='Età utente'),
        ),
        migrations.AlterField(
            model_name='testexecution',
            name='duration',
            field=models.DurationField(verbose_name='Durata'),
        ),
        migrations.AlterField(
            model_name='testexecution',
            name='execution_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name="Data d'esecuzione"),
        ),
        migrations.AlterField(
            model_name='testexecution',
            name='given_answer',
            field=models.ManyToManyField(related_name='test_executions', to='quizPlugin.answer', verbose_name='Risposte date'),
        ),
        migrations.AlterField(
            model_name='testexecution',
            name='ip',
            field=models.GenericIPAddressField(verbose_name='Indirizzo IP utente'),
        ),
        migrations.AlterField(
            model_name='testexecution',
            name='note',
            field=models.TextField(verbose_name='Note di revisione'),
        ),
        migrations.AlterField(
            model_name='testexecution',
            name='revision_code',
            field=models.CharField(blank=True, editable=False, max_length=12, unique=True, verbose_name='Codice di revisione'),
        ),
        migrations.AlterField(
            model_name='testexecution',
            name='revision_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data di revisione'),
        ),
        migrations.AlterField(
            model_name='testexecution',
            name='score',
            field=models.IntegerField(verbose_name='Punteggio'),
        ),
        migrations.AlterField(
            model_name='testexecution',
            name='sex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_executions', to='quizPlugin.sex', verbose_name='Sesso utente'),
        ),
        migrations.AlterField(
            model_name='testexecution',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_executions', to='quizPlugin.test', verbose_name='Test relativo'),
        ),
    ]
