# Generated by Django 5.2.1 on 2025-05-26 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizPlugin', '0011_alter_testexecution_age_alter_testexecution_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testexecution',
            name='given_answer',
        ),
        migrations.AlterField(
            model_name='givenanswer',
            name='test_execution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_answers_through', to='quizPlugin.testexecution'),
        ),
        migrations.AlterField(
            model_name='testexecution',
            name='score',
            field=models.IntegerField(default=0, verbose_name='Punteggio'),
        ),
    ]
