# Generated by Django 5.2.1 on 2025-05-26 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizPlugin', '0012_remove_testexecution_given_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='score',
            field=models.IntegerField(choices=[(-1, 'Errore Grave'), (0, 'Errore'), (1, 'Corretto')]),
        ),
    ]
