# Generated by Django 5.2.1 on 2025-06-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizPlugin', '0013_alter_answer_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='score',
            field=models.FloatField(),
        ),
    ]
