# Generated by Django 5.2.1 on 2025-06-09 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizPlugin', '0014_alter_answer_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='min_score',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='testexecution',
            name='score',
            field=models.FloatField(default=0, verbose_name='Punteggio'),
        ),
    ]
