# Generated by Django 5.2.1 on 2025-06-10 13:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizPlugin', '0015_alter_test_min_score_alter_testexecution_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='correction',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Correzione della risposta'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=ckeditor.fields.RichTextField(verbose_name='Testo della domanda'),
        ),
    ]
